### PR TITLE
Write prose for the home page

### PR DESCRIPTION
**Pull request by wchargin**
Summary:
@decentralion and I have spent a bunch of time on this prose, and we
think that it’s pretty good. Let’s put some content on our otherwise
bare site.

Test Plan:
Running `yarn start` suffices.

Paired with @decentralion.

wchargin-branch: home-page-prose

### CODE REVIEW

**Comment by decentralion** [comment]
FYI @campoy, @vmarkovtsev, @mkosowsk, @owocki, @ajbouh - now that [sourcecred.io](sourcecred.io) is live and have some content, we consider the sourcecred alpha to have started :D

**Comment by mkosowsk** [comment]
@decentralion Great! Will be watching with keen interest 👍

**Comment by vmarkovtsev** [comment]
Cool! How about sorting the PageRank results in descending order?

**Comment by wchargin** [comment]
@vmarkovtsev The PageRank results are sorted in descending order, but the scores are negative-log-score, so lower is better. We should clarify this in the UI.

**Pull request merged**
