### PR TITLE
Integrate the identity plugin

### PR DESCRIPTION
**Pull request by decentralion**
This commit integrates the identity plugin, which was created in #1384.
It does this by adding explicit identity fields to the project
configuration, which are then applied when loading the graph in
`api/load.js`.

The actual integration is quite straightforward.

Test plan: The underlying logic is thoroughly tested; I added one new
test case to verify that it is integrated properly. Since the project
compat has changed, I've updated all the snapshots. Prior to merging
this PR, I will produce one "integration test", using this code to do
identity resolution for a real project (i.e. on the SourceCred instance
itself).

### CODE REVIEW

**Comment by decentralion** [comment]
@Beanow / @vsoch it looks like this commit is consistently failing the docker publish test, see [failure](https://circleci.com/gh/sourcecred/sourcecred/2218?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

Can you take a look into what's going wrong?

**Comment by Beanow** [comment]
It actually seems like a flake on CircleCI's side to me. Recent builds of the same command `docker/publish-1` have worked. And none of our code is executed yet. Just Circle allocating a VM for the job.

**Comment by Beanow** [comment]
Actually it is a real issue, possibly a bug with the docker orb we're using.
On other recent runs, like https://circleci.com/gh/sourcecred/sourcecred/2227#config/containers/0 it expands the configuration into:
```
  docker/publish-1:
    machine:
      docker_layer_caching: false
      image: ubuntu-1604:201903-01
```

While this run it expands into:
```
  docker/publish-1:
    machine:
      docker_layer_caching: false
      image: sourcecred/sourcecred
```

**Comment by Beanow** [comment]
I've submitted a bugreport of this happening here https://github.com/CircleCI-Public/docker-orb/issues/19

And have a mitigation here: https://github.com/sourcecred/sourcecred/tree/pr/anti-flake-docker-orb

If the issue persists, you may try cherry picking that commit / merging it separately.

**Comment by vsoch** [comment]
Where do you see it's failing publish? I see an error at `yarn test --ci` but maybe I missed it?

There was another weird CircleCI error that I saw yesterday, let me see if I can find it:

```
Build-agent version 1.0.15410-75b89bda (2019-09-13T15:43:07+0000)
Creating a dedicated VM with nushell/nu-base image
failed to create host: Image nushell/nu-base is not supported

failed to create host: Image nushell/nu-base is not supported
```
In this case, also using the Docker Publish orb, and it didn't even get to set up the environment.

**Comment by Beanow** [comment]
It's the same error as you're getting @vsoch and what I reported at https://github.com/CircleCI-Public/docker-orb/issues/19

If you go to the "Configuration" tab of such a failed build, you'll probably see the `nushell/nu-base` image got incorrectly passed onto the machine executor VM image. Which isn't right because this should be a VM image for a docker host.

**Comment by vsoch** [comment]
That's so strange! There haven't been changes to the Orb itself (that repo) since July 23rd, so it must be something internal at Circle. I'm not sure how responsive they are there, because I opened a PR on that exact repo 9 days ago and it's been :cricket: .

**Comment by decentralion** [comment]
@vsoch @Beanow it wound working fine (both builds passed). not sure what changed.

good example here of references not corresponding super well with cred for the PR, btw :P

**Pull request merged**
