### PR TITLE
Delete publish workflow

### LINKED ISSUE #2337: Publish action broken, failing on every commit
[Quoth myself][1]:

> This appears to break the action: it’s failing at every commit with
> 
> > **Error**
> > No event triggers defined in `on`
> 
> Sample failure:
> https://github.com/sourcecred/sourcecred/actions/runs/284710170
> 
> Please fix?

I continue to get emails about this on every commit. One recent one:
<https://github.com/sourcecred/sourcecred/actions/runs/288286292>

[1]: https://github.com/sourcecred/sourcecred/pull/2301#issuecomment-702908924

### PR DESCRIPTION
**Pull request by topocount**
github throws an error because no event triggers are present in the workflow file. 
We should just delete it.

Fixes #2337.

test plan: the publish file's presence should no longer trigger an
attempted workflow. This can be verified by viewing clicking on the
"checks" tab in the pull request

### CODE REVIEW

**Comment by topocount** [comment]
I'm also open to the possibility of simply deleting this file and letting it live solely in the Git history

**Review by decentralion — COMMENTED** [review]
I vote delete.

**Comment by hammadj** [comment]
Curious, what are we doing now to handle releases? Out of the loop since I was MIA last week

**Comment by topocount** [comment]
> Curious, what are we doing now to handle releases? Out of the loop since I was MIA last week

@hammadj we're taking advantage of OTP auth to secure npm so it's manual. I'm going to transpose this to prepublish scripts soon:
1. Update version in package.json (i think that's the only place)
2. Commit and tag
3. Prepublish, build the package locally
4. Go to canary instances (e.g. sourcecred/cred, sourcecred/template-instance) and rebuild those using the local package
5. Test that our canary instances build, load / score, and have fully functional frontends (ledger admin, weights, etc -- embarassing if we push regressions)
6. If they work, push the tag, npm publish
7. Draft release on GitHub pointing to the already-made tag

**Review by wchargin — COMMENTED** [review]
I vote delete. Dead code should be buried; can always revive.

**Review by wchargin — APPROVED** [review]
modulo updating title/description

**Comment by wchargin** [comment]
Thanks!

**Pull request merged**
