### PR TITLE
Flow typed docs script

### PR DESCRIPTION
**Pull request by youngkidwarrior**
# Description
Dependant on #2435 
Flow typing the local generated docs script. Using the flow comment type structure because we need it to work as plain javascript.

# Test Plan
- Run `yarn docs` to generate the docs folder
- Ensure it logs `success` for all generated docs

### CODE REVIEW

**Comment by BrianBelhumeur** [comment]
Looks like you accidentally committed your `.DS_Store` file

**Review by decentralion — COMMENTED** [review]
The PR description and test plan need to communicate what the change does, and how the reviewer can be confident that the change is correct. Right now, that's not really possible--reading the description I don't actually know what this PR does or how to test it. Does it add a command that generates docs? How can I view those docs? How will those docs get consumed or integrated elsewhere?

Please re-write this so there's a test plan. It could be something like:

- Run the following command to generate docs
- Run the following command to view the docs
- Explore the docs and confirm they are correctly generated from the code comments

It would also be nice to have a screenshot or such of how the docs look once generated.

See: [the relevant section of CONTRIBUTING.md](https://github.com/sourcecred/sourcecred/blob/master/CONTRIBUTING.md#when-writing-commit-messages)

**Comment by youngkidwarrior** [comment]
@decentralion my bad on the test plan! 

This PR is a dependent on #2435 which has all the stuff you asked for (description of changes, video example, etc)

**Review by hammadj — COMMENTED** [review]
Changed the base of this PR to point at the branch for #2435 so that both the changes dont show in the PR. Looks mostly good, but there's an update to yarn.lock that doesn't belong here since there wasn't change to package.json.

**Pull request merged**
