### PR TITLE
Add serialization to TimelineCredScores

### PR DESCRIPTION
**Pull request by decentralion**
Right now the serialization is super trivial, we just attach a compat
header. In the future, we can try encoding the float64 arrays as
bytestrings to save space.

This will be used by the CredGraph module, as in #1657

Test plan: Unit tests included; `yarn test` passes.

### CODE REVIEW

**Comment by Beanow** [comment]
To make review easier: I've never tried serializing `Float64Array` as is. Can you provide an example of how a json serializer/parser goes about it?

**Comment by decentralion** [comment]
Sure. It's terrible. :)

```js
> JSON.stringify(new Float64Array([1,2,Math.PI]))
"{"0":1,"1":2,"2":3.141592653589793}"
```

**Comment by Beanow** [comment]
> Sure. It's terrible. :)
> 
> ```js
> > JSON.stringify(new Float64Array([1,2,Math.PI]))
> {"0":1,"1":2,"2":3.141592653589793}
> ```

:scream: wouldn't that `JSON.parse` to be of type `number[]`?

**Comment by decentralion** [comment]
You're right... this doesn't actually work from a type perspective. 

```
JSON.parse(JSON.stringify(new Float64Array([1]))).constructor
ƒ Object() { [native code] }
```

I'll re-work it.

**Comment by decentralion** [comment]
I've pushed a second commit addressing the issue you found @beanow. As an added benefit, the new representation is less grotesquely wasteful of space. :)

**Comment by decentralion** [comment]
Sure thing. It's used for the CredGraph module, see https://github.com/sourcecred/sourcecred/pull/1657

**Comment by Beanow** [comment]
Edited OP, had a link to the wrong number :smile:

**Pull request merged**
