### PR TITLE
testing: Set Up Cypress

### PR DESCRIPTION
**Pull request by topocount**
Cypress is a versatile testing framework that can be used for unit and
end-to-end frontend tests. It utilizes mocha and chai libraries for
writing tests.

The flow libdefs for all of these libraries are quite lacking, however
and I'm strongly considering using a .flow file that is localized to the
cypress folder to resolve this, and additionally, mitigate collisions
with Jest.

Cypress has not been hooked up to the larger testing sequence we have,
	as no useful tests have been written yet.
for an example test see #2437 

test plan: ensure all existing automated test pass

### CODE REVIEW

**Review by BrianBelhumeur — APPROVED** [review]
LGTM. I'm not well-versed with typing just yet, but I assume you pulled most / all of the typing definitions from within the cypress package?

**Review by decentralion — COMMENTED** [review]
I feel kind of weird about pulling in chai and mocha. Are they hard deps of cypress?

**Comment by topocount** [comment]
> I feel kind of weird about pulling in chai and mocha. Are they hard deps of cypress?

I do too, @decentralion . I discussed this with @wchargin and will create definitions that are local to the cypress folder.

**Comment by topocount** [comment]
Closing for now. Will reopen when I get back to working on this

**Pull request closed without merging**
