### PR TITLE
update_snapshots: fix Discourse key check

### PR DESCRIPTION
**Pull request by wchargin**
Summary:
This was doing exactly the wrong thing, attempting to update snapshots
whenever the Discourse API token was _not_ present.

Test Plan:
Running `env -u DISCOURSE_TEST_API_KEY ./scripts/update_snapshots.sh`
now successfully updates non-Discourse snapshots, rather than emitting
an error, “Please set the DISCOURSE_TEST_API_KEY environment variable.”.

wchargin-branch: update-snapshots-discourse

### CODE REVIEW

**Comment by vsoch** [comment]
Is this something I could test? I am admin on a discourse install, and it would be cool to generate the plots! @Beanow would a widget work too with the updates here?

**Comment by Beanow** [comment]
As this is already merged, I posted a reply here https://github.com/sourcecred/widgets/issues/30 @vsoch

**Comment by vsoch** [comment]
Thanks @Beanow !

**Comment by decentralion** [comment]
@vsoch I want to have the Discourse plugin usable by the end of the week. I'll keep you in the loop!

**Pull request merged**
