### PR TITLE
Move to multiple servers with mirror options.

### PR DESCRIPTION
**Pull request by Beanow**
Continues from #1432 

As discussed in #1426, this adds multiple server support per project. Including loading in parallel and CLI updates. It anticipates on what the `MirrorOptions` object will be, as this is included in the project `0.4.0` format.

It creates an interesting compatibility issue with the identities plugin though, as multiple servers can't be interpreted by the `discourse/@username` aliases.

Test plan:
```
yarn install
yarn backend

node bin/sourcecred.js discourse \
  https://sourcecred-test.discourse.group \
  https://discourse.sustainoss.org \
  https://discourse.sourcecred.io
```

### CODE REVIEW

**Comment by decentralion** [comment]
This PR adds a feature (multiple server support) which might introduce a number of subtle bugs (you pointed out one re: the identity plugin, and there may be more). Do we know of any use-cases or needs for this feature at the moment?

If we do want to merge it now, should also spend some time thinking about potential bugs it will introduce, and put some effort towards fixing them now while the context is fresh. But if we don't have any users for this feature, I don't think that's a good use of time.

**Comment by Beanow** [comment]
Aside from the one with identity, there's several places in the explorer that assumes one discourse server. You're right that I don't know of any communities that have more than one forum, but we have had #1415 multiple orgs for github which I wouldn't have assumed for most communities either.

Not having this feature will make flowing cred between these forums, reference detection, instance config, etc. harder to do later as features stack up with the one-forum assumption. This would put pressure to break that assumption at the project level.

We could push this back as part of deep-than-wide. But I think breaking the assumption earlier will also help towards finding good APIs and fixing those assumption bugs. As the same would apply to Discord, where we have one, but I'm sure there will be communities with more.

**Comment by decentralion** [comment]
Cross-community cred isn't something I'm focused on right now (it raises a lot of thorny issues around governance) but it is definitely something that warrants thought and experimentation. And you raise a good point around how making this change later will become more expensive, after we've had more time to assume that there's always one server.

However, at the moment we're focused on work that gives high leverage to SourceCred, by making SourceCred better at self-organizing the labor (e.g. via initiatives and champions) to direct coordinate engineering work. So in a sense the current "cost of engineering work" is very high, since we have little engineering bandwidth, but if we invest it well the cost will decrease a lot in the future.

Therefore, we should be willing to punt on features that don't give us much short term benefit, even if they will grow more expensive over time, if the rate at which they grow expensive is lower than the rate our resources will grow. and I don't think that this change will grow that much more expensive over time.

This was all a very complicated way of saying: "Yeah, deep then wide, I think we should punt on this for now."

**Comment by decentralion** [comment]
@beanow shall we close this as wontfix for now?

**Comment by Beanow** [comment]
> @Beanow shall we close this as wontfix for now?

#1451 is the alternative implementation. I'll indeed close this as wontfix.

**Pull request closed without merging**
