### PR TITLE
Initial version of the Cred Explorer

### PR DESCRIPTION
**Pull request by dandelionmane**
Sets up an initial cred explorer that looks at Git commit data

- uses git commit data as generated by `experiments/01_commit_graph_dump.ipynb`
- displays a file explorer, which lets you navigate the file tree by expanding/collapsing dirs, and select a path via double clicking (changes background color)
- displays a user explorer, which shows a sorted list of authors and cred amounts for the selected file path

The commit-wrangling logic is in commitUtils.js and has typechecking (via flow) and some basic testing.
The frontend is built with react; setup was bootstrapped via create-react-app.

Test plan:

```
cd explorer;
yarn install; # get dependencies
yarn flow; # check that types check out, then ctrl+c
yarn test; # check that tests pass, then ctrl+c
yarn start; # go to localhost:3000 and click around
```

expected behavior: there's a file explorer that shows TensorBoard file structure on the left. you can click the buttons to explore directory, and you can click files to select that path. on the right, it shows you the users that contributed to that directory and their cred for those commits.

note: the ui is very crude.

### CODE REVIEW

**Comment by dandelionmane** [comment]
@wchargin If you try to load the app as present here, it errors out at runtime. It seems that the data.json file we've been using has garbage data in the commits. To illustrate, load `src/data.json` as `j` in Python and examine the following path:

```
 j['commits']['2a7148008e5d5caf91dcddf67eb3a69a602c87ae']['stats'].keys()[:10]

[
u'{components => tensorboard/components}/tf_dashboard_common/reload-behavior.ts', 
u'{plugins => tensorboard/plugins}/base_plugin.py', 
u'{backend => tensorboard/backend}/http_util_test.py', 
u'{components => tensorboard/components}/tf_graph_info/tf-graph-icon.html', 
u'{components => tensorboard/components}/tf_storage/BUILD', 
u'{components => tensorboard/components}/tf_scalar_dashboard/tf-scalar-dashboard.html',
u'{components => tensorboard/components}/tf_graph_dashboard/tf-graph-dashboard.html', 
u'{plugins => tensorboard/plugins}/projector/projector_plugin_test.py', 
u'{components => tensorboard/components}/tf_option_selector/BUILD', 
u'{scripts => tensorboard/scripts}/__init__.py
']
```
It looks like the script is mis-parsing the output from Git and recording rename paths as file paths. Up for fixing it and putting in a new data blob?

**Comment by dandelionmane** [comment]
@wchargin PTAL :)

**Comment by dandelionmane** [comment]
On second though... maybe hold off review, I'll split this into smaller & more manageable pieces tomorrow.

**Comment by wchargin** [comment]
> On second though... maybe hold off review, I'll split this into smaller & more manageable pieces tomorrow.

Cool; I'm happy to wait, though at a glance it looks like most of the uber-PR is due to the `create-react-app` output.

Perhaps it would be useful to check in the initial `create-react-app` output completely unchanged (which can be merged with minimal review), and then a few separate commits on top of that? Or, if you had something else in mind, go for it.

**Comment by dandelionmane** [comment]
Yep, that's basically what I did - see #13 and #14.

I also directly merged #12, which was tweaking the data generator script and committing the TensorBoard data as a test case.

**Comment by dandelionmane** [comment]
Closing this PR in favor of the new ones.

**Pull request closed without merging**
