### PR TITLE
Make SourceCred a public package

### PR DESCRIPTION
**Pull request by decentralion**
I'm mostly motivated by wanting to get greenkeeper lockfile
auto-updating working (see #1269) although this is also a first step
towards making SourceCred usable from NPM (#1232).

For now, see this as us making sure we claim the sourcecred package name
on npm (see: https://www.npmjs.com/package/sourcecred).

I also fixed the license spec so that it's valid SPDX.

### CODE REVIEW

**Comment by wchargin** [comment]
Thank you! Hope this fixes the lockfile issues.

**Comment by wchargin** [comment]
Looks like it didn’t? #1287

**Comment by decentralion** [comment]
Indeed. Maybe it's just in a bad state? I'm attempting a "greenkeeper reset".

**Comment by decentralion** [comment]
Still an issue in the reset greenkeeper PR: https://github.com/sourcecred/sourcecred/pull/1289

I emailed support@greenkeeper.io, let's see if they help.

**Comment by Beanow** [comment]
:+1:
Be sure to claim `@sourcecred` on NPM as well if we're doing namesquating.

**Comment by decentralion** [comment]
Yep, I've had `@sourcecred` on NPM for a while now.

**Pull request merged**
