### PR TITLE
Support `sourcecred go` out of the box

### PR DESCRIPTION
**Pull request by topocount**
This PR allows `sourcecred go` to succeed out of the box in the template instance. Each small bugfix and refactor needed to make this happen is contained in its own semantically atomic commit. 

test plan:
1. yarn build
2. run `scdev go` in the template-instance repo

### CODE REVIEW

**Review by decentralion — COMMENTED** [review]
What are the unintended side effects we're trying to prevent? What are the root causes of those side effects? Are there other code paths that trigger the same side effects, which aren't fixed by this change?

While I don't object to this change, it feels a little hacky and ad hoc to me. If we're going to be validating the bundledPlugins, we should probably also verify that each putative bundled plugin is actually a valid plugin.

**Comment by topocount** [comment]
@decentralion this is basically a an effort to prevent #2460. Initially I set out to make changes everything runs without error with no plugins (because why shouldn't that be okay?), but The sourcecred dependency-minting config and the default `[]` in the empty ledger file were two special cases that would need to be addressed in these changes. 

I've found that naive users can fall into a hopeless loop trying to test out the example instance, where the first `go` call deletes empty array from ledger.json each time `graph` runs, and then once they realize they need to replace that to run the `score` command, they'll get another error because the sourcecred dependency node throws this error on `score`: `Error: no Account for identity: 2zWwkGHnBGXmEcYneeWAzw`

I figured that, rather than trying to accommodate these and potentially more special cases, we could prevent users from doing something that would just lead them down a path of opaque errors, and could also direct them towards setting up the instance properly. 

I'm happy to add some validation for plugins at this point in the code, but I'm aware that it already occurs later as well. This change is mostly meant to minimize the amount of friction users encounter while setting up an instance,

**Comment by decentralion** [comment]
> Initially I set out to make changes so everything runs without error with no plugins (because why shouldn't that be okay?)

My @wchargin simulator strongly favors making this OK.

> but The sourcecred dependency-minting config and the default [] in the empty ledger file were two special cases that would need to be addressed in these changes.

Yeah, those sound like root issues that should be fixed, rather than papering over them (which this PR does, imo).

> the first go call deletes empty array from ledger.json each time graph runs

Why does it do that? Can we fix that?

**Comment by topocount** [comment]
> > Initially I set out to make changes so everything runs without error with no plugins (because why shouldn't that be okay?)
> 
> My @wchargin simulator strongly favors making this OK.
> 
> > but The sourcecred dependency-minting config and the default [] in the empty ledger file were two special cases that would need to be addressed in these changes.
> 
> Yeah, those sound like root issues that should be fixed, rather than papering over them (which this PR does, imo).
> 
@decentralion While I am in favor making the "base case" (clean template instance) run cleanly, I don't think it's particularly helpful for users for that to happen, unless we log a message after everything completes with similar instructions to what I pushed. I think it's important that we provide users toying around with the instance with some direction after everything runs, since it decreases needed support labor and helps them to get started on their own.

**Review by decentralion — COMMENTED** [review]
Cool, these changes look good to me now. I recommend splitting them into 4 smaller PRs which each have a well-defined scope. This will be slightly more work since each PR will need its own test plan, which is a Good Thing :). (For the PRs with unit tests, those likely suffice for the test plan).

This will also get you more Cred, which IMO is quite well deserved.

**Comment by topocount** [comment]
Closing in favor of #2485, #2486, #2487, 2488

**Pull request closed without merging**
