### PR TITLE
Add manifesto explaining the SourceCred vision

### PR DESCRIPTION
**Pull request by decentralion**
If we merge this, I plan to replace the contents of our website with
this manifesto.

Test plan: Review for content, typos, and formatting.

### CODE REVIEW

**Comment by decentralion** [comment]
@wchargin please let me know what you think. If it passes your sniff test, I'll invite some more people to review (including from OpenCollective/GitCoin/OSCoin to make sure they are happy being referenced).

**Comment by decentralion** [comment]
Offline, @wchargin and I discussed his concern that the [first draft of the manifesto](https://github.com/sourcecred/sourcecred/blob/7b7ef8b7984dc6aa972867715c2807c5f961779d/MANIFESTO.md) as visible in the commits on this PR are too tightly coupled with cryptonetworks, and could be off-putting to the large population that is reasonably skeptical of all things crypto.

I've taken a stab at writing another draft, which is still more direct / more clearly motivates
SourceCred's existence than our [current copy](https://sourcecred.io/), but decreases
the coupling to crypto concepts.

@wchargin, please tell me what you think. I'd also love feedback from @anoemi, @ianjdarrow @nayafia and @devonzuegel

```
# SourceCred Manifesto

The open-source movement is inspiring. It's amazing that some of our best
technology is developed in the open, and made freely available to everyone.
Today, open-source software is depended on everywhere, from core infrastructure
for Google and Facebook down to personal WordPress blogs.

Despite this, open-source sees [chronic underinvestment], because we don't have
systems that reward people who contribute to the open-source commons. Many
open-source projects are run entirely by dedicated volunteers. Sometimes that
means that [critical bugs](heartbleed) slip through the cracks. Other times it
just means burnout among open-source maintainers, and underinvestment in the
digital world's critical infrastructure.

There's a growing movement to make open-source sustainable, by creating systems
that pay the maintainers and contributors. For example, [Open Collective] makes
it easy for projects to raise money, and [Open Source Coin] plans to make a
cryptocurrency that backs open-source.

These projects all have a shared problem: it's difficult to fairly split the
credit in a project between its contributors. How much credit should the
founder get? What about the contributor who re-wrote the documentation, or that
person who keeps fixing the build? Without an answer to these questions, it's
hard to fairly reward contributors, whether through novel cryptocurrencies or
old-fashioned dollars. We need a community-driven system that can fairly
recognize the contributors to a project, and quantitatively appraise their
contributions. It needs to be fair and transparent, and capable of recognizing
both technical and nontechnical contributions for a project.

SourceCred is our attempt to build such a system. It operates by modeling all
of the individual contributions that make up a project—for example, writing a
pull request, fixing the build, or organizing a meetup. These contributions
are organized in a network, which shows how they depend on and enable other contributions.
Then, contributions earn *cred* based on the cred of the contributions that they 
enabled.

Right now, our [prototype] can do this with data from Git and GitHub. It imports
every pull request, issue, comment, and commit, and assigns cred to them (and
their authors) based on their relationships. We plan to add a lot more sources
of signal in the future, from scanning the function call graph of a project's
source code, allowing users to add "spotlight" nodes that recognize contributions,
like organizing a meetup, that don't make it into Git or GitHub.

We're excited to develop SourceCred into a vital tool for recognizing and rewarding
open-source contributors. If you'd like to get involved, please check out our [GitHub],
and say hello in our [Discord chat] or our [Discourse forum].
```

**Comment by wchargin** [comment]
I haven't forgotten about this; was thinking about it yesterday. Will read and respond when I get a chance.

**Comment by wchargin** [comment]
This is way much better. Thanks!

Can’t give it an official review, so:

> ```markdown
> # SourceCred Manifesto
> ```

As discussed offline, “manifesto” is a very loaded term. Can you explain
to me what you’re trying to achieve by invoking it? We currently have
“SourceCred vision”. Is this missing something?

> ```markdown
> 
> The open-source movement is inspiring. It's amazing that some of our best
> technology is developed in the open, and made freely available to everyone.
> Today, open-source software is depended on everywhere, from core infrastructure
> for Google and Facebook down to personal WordPress blogs.
> 
> Despite this, open-source sees [chronic underinvestment], because we don't have
> systems that reward people who contribute to the open-source commons. Many
> open-source projects are run entirely by dedicated volunteers. Sometimes that
> means that [critical bugs](heartbleed) slip through the cracks. Other times it
> ```

s/`(heartbleed)`/`[heartbleed]`/ almost certainly

> ```markdown
> just means burnout among open-source maintainers, and underinvestment in the
> digital world's critical infrastructure.
> 
> There's a growing movement to make open-source sustainable, by creating systems
> that pay the maintainers and contributors. For example, [Open Collective] makes
> it easy for projects to raise money, and [Open Source Coin] plans to make a
> cryptocurrency that backs open-source.
> 
> These projects all have a shared problem: it's difficult to fairly split the
> credit in a project between its contributors. How much credit should the
> ```

s/between/among/. Also, _split_ doesn’t feel exactly right to me, but I
can’t think of anything better off the top of my head. 

> ```markdown
> founder get? What about the contributor who re-wrote the documentation, or that
> person who keeps fixing the build? Without an answer to these questions, it's
> hard to fairly reward contributors, whether through novel cryptocurrencies or
> old-fashioned dollars. We need a community-driven system that can fairly
> recognize the contributors to a project, and quantitatively appraise their
> contributions. It needs to be fair and transparent, and capable of recognizing
> both technical and nontechnical contributions for a project.
> 
> SourceCred is our attempt to build such a system. It operates by modeling all
> of the individual contributions that make up a project—for example, writing a
> pull request, fixing the build, or organizing a meetup. These contributions
> are organized in a network, which shows how they depend on and enable other contributions.
> ```

Our current wording uses the term “graph” (with a Wikipedia link) and
mentions that we use PageRank. Rationale for replacing with just
“network”? I don’t necessarily object, though I’m somewhat surprised.

> ```markdown
> Then, contributions earn *cred* based on the cred of the contributions that they 
> enabled.
> 
> Right now, our [prototype] can do this with data from Git and GitHub. It imports
> every pull request, issue, comment, and commit, and assigns cred to them (and
> ```

worth mentioning reviews, or “etc.”? (`SELECT DISTINCT typename FROM objects`)

> ```markdown
> their authors) based on their relationships. We plan to add a lot more sources
> ```

nit: s/a lot/many/ sounds better to my ear

> ```markdown
> of signal in the future, from scanning the function call graph of a project's
> ```

Syntax error: “from” without matching “to”. Also, moderate preference
for avoiding “from…to” with categoricals. Suggest “such as […] and […]”.

> ```markdown
> source code, allowing users to add "spotlight" nodes that recognize contributions,
> like organizing a meetup, that don't make it into Git or GitHub.
> 
> We're excited to develop SourceCred into a vital tool for recognizing and rewarding
> open-source contributors. If you'd like to get involved, please check out our [GitHub],
> and say hello in our [Discord chat] or our [Discourse forum].
> ```

**Comment by decentralion** [comment]
I showed [the above draft](https://github.com/sourcecred/sourcecred/pull/936#issuecomment-437217377) to @jbenet and he offered the following feedback
- Overall, looks really good + accessible, would ship it as it is
- "the top contributors" can rub people the wrong way, as it artificially segregates into top/not top. Suggest putting the focus on contributions rather than contributors
- The copy doesn't mention that projects can configure SourceCred, and use it to reflect + communicate their own priorities

This comment is effectively paired with @jbenet

**Comment by nayafia** [comment]
I like the landing page style copy *much* better 👍 

> "the top contributors" can rub people the wrong way, as it artificially segregates into top/not top. Suggest putting the focus on contributions rather than contributors

Agreed, could even just say `It's hard to tell who contributes to an open-source project`

**Comment by decentralion** [comment]
Here's another draft, which incorporates Juan's feedback:

```
It's hard to tell who is making valuable contributions to an open-source
project. Counting lines of code doesn't cut it— what about the contributor
whose few commits are disproportionately important, or who triages incoming
issues, or fixes the build?

SourceCred shines a light on those contributors. It imports a project's
development history from Git and GitHub, and assigns "cred" to every
contribution—from the biggest pull request to the smallest comment.
Contributions are valued based on the importance of the contributions that
reference or depend on them, as well as on social feedback like 👍reactions👍.

Under the hood, SourceCred organizes contributions into a [graph] and then runs
[PageRank] on them. SourceCred is built around a modular plugin architecture,
so it can be extended to include more kinds of contributions, like
StackOverflow answers, posts on a mailing list, or kudos from the community.
SourceCred is highly configurable, so projects can use it to express what they
find most valuable. One project might assign a lot of cred for new features;
another might put more emphasis on improving testing or documentation.

You can run SourceCred on your project by following instructions in our [README],
or you can check out some [examples] that we're hosting. For example, here's
[the cred analysis for SourceCred itself].

SourceCred is, of course, an open-source project. It's being developed by
[Protocol Labs]. We hope that by shining a light on open-source contributors,
we can help make the open-source ecosystem more sustainable. 🌱🌼 

We'd love to have your help along the way. Please check out our [GitHub] and
say hello in our [Discord channel].
```

> SourceCred is highly configurable, so projects can use it to express what they
> find most valuable. One project might assign a lot of cred for new features;
> another might put more emphasis on improving testing or documentation.

It's true that SourceCred is highly configurable, but right now it's not possible to put different weights on new features or testing or whatnot. I could weaken the statement to "SourceCred aims to be highly configurable" to make it more literally accurate. What do y'all think?

**Comment by decentralion** [comment]
Obsoleted by https://github.com/sourcecred/mission/pull/8.

**Pull request closed without merging**
