### PR TITLE
github: retry rate limits every 15 minutes

### LINKED ISSUE #2201: GitHub plugin load should not die due to rate limit
When we're loading the GitHub plugin, it currently dies when the API rate limit is exceeded. When the user is working with a local cache, this is OK because they can wait an hour and re-try. However, when this is happening on a GitHub action, it would be far better if the job would simply wait an hour and then continue loading, so that it would eventually succeed (and save all the data in cache).

I believe we should add the wait/and/retry logic here:
https://github.com/sourcecred/sourcecred/blob/cd92a24ba1456163040124868a5d9944dcf9d4b8/src/plugins/github/fetchGithubRepo.js#L263-L268

### PR DESCRIPTION
**Pull request by wchargin**
Summary:
When a query in `fetchGithubRepo` fails because the rate limit has been
exceeded, it will now be retried after 15 minutes rather than simply
failing the load.

Fixes #2201. Thanks to #2312 for drafting an initial approach to this
problem.

Test Plan:
The waiting functionality is tested in `util/retry.test.js`, which
covers the policy change. As an end-to-end test for the new logic,
I patched the code to only wait 1 minute instead of 15 and to retry up
to 60 times, and to add logging (patch below). Then, I tried to load
GitHub data for [the `1Hive/pollen` instance][1]. After my quota
exhausted, retries began, with the desired frequency. On the hour, the
rate limit refreshed, and the job completed:

```
  GO   sourcecred/github: github: loading 1Hive/uniswap-info
 DONE  sourcecred/github: github: loading 1Hive/uniswap-info: 2m 1s
  GO   sourcecred/github: github: loading 1Hive/uniswap-v2-subgraph
 DONE  sourcecred/github: github: loading 1Hive/uniswap-v2-subgraph: 53s
  GO   sourcecred/github: github: loading 1Hive/uniswap-interface
@1601789998.109 {"error":{"errors":[{"message":"API rate limit exceeded","type":"RATE_LIMITED"}]},"retry":false,"type":"RATE_LIMIT_EXCEEDED"}
@1601790058.523 {"error":{"errors":[{"message":"API rate limit exceeded","type":"RATE_LIMITED"}]},"retry":false,"type":"RATE_LIMIT_EXCEEDED"}
@1601790118.998 {"error":{"errors":[{"message":"API rate limit exceeded","type":"RATE_LIMITED"}]},"retry":false,"type":"RATE_LIMIT_EXCEEDED"}
@1601790179.403 {"error":{"errors":[{"message":"API rate limit exceeded","type":"RATE_LIMITED"}]},"retry":false,"type":"RATE_LIMIT_EXCEEDED"}
...
@1601791085.875 {"error":{"errors":[{"message":"API rate limit exceeded","type":"RATE_LIMITED"}]},"retry":false,"type":"RATE_LIMIT_EXCEEDED"}
@1601791146.259 {"error":{"errors":[{"message":"API rate limit exceeded","type":"RATE_LIMITED"}]},"retry":false,"type":"RATE_LIMIT_EXCEEDED"}
 DONE  sourcecred/github: github: loading 1Hive/uniswap-interface: 25m 31s
  GO   sourcecred/github: github: loading 1Hive/honeyswap-unipool-frontend
 DONE  sourcecred/github: github: loading 1Hive/honeyswap-unipool-frontend: 8439ms
  GO   sourcecred/github: github: loading 1Hive/unipool
 DONE  sourcecred/github: github: loading 1Hive/unipool: 15s
 DONE  loading sourcecred/github: 52m 6s
```

<details>
<summary>Patch used for testing purposes</summary>

```diff
diff --git a/src/plugins/github/fetchGithubRepo.js b/src/plugins/github/fetchGithubRepo.js
index 866625b1..c76a5f50 100644
--- a/src/plugins/github/fetchGithubRepo.js
+++ b/src/plugins/github/fetchGithubRepo.js
@@ -6,6 +6,7 @@

 import Database from "better-sqlite3";
 import fetch from "isomorphic-fetch";
+import jsonStringify from "json-stable-stringify";

 import {type RepoId, repoIdToString} from "./repoId";
 import {Mirror} from "../../graphql/mirror";
@@ -213,18 +214,19 @@ async function retryGithubFetch(
     jitterRatio: 1.2,
     // We wait in 15-minute intervals, and quotas reset every hour, so
     // we shouldn't give up before waiting 4 times.
-    maxWaits: 4,
+    maxWaits: 60,
   };
   const retryResult = await retry(async () => {
     try {
       return {type: "DONE", value: await tryGithubFetch(fetch, fetchOptions)};
     } catch (errAny) {
       const err: GithubResponseError = errAny;
+      console.warn(`@${(Date.now() / 1000).toFixed(3)}`, jsonStringify(err));
       if (err.type === "RATE_LIMIT_EXCEEDED") {
         // Wait in 15-minute increments. TODO(@wchargin): Ask GitHub
         // when our token resets (`{ rateLimit { resetAt } }`) and wait
         // until just then.
-        const delayMs = 15 * 60 * 1000;
+        const delayMs = 1 * 60 * 1000;
         return {type: "WAIT", until: new Date(Date.now() + delayMs), err};
       }
       if (err.retry) {
```

</details>

[1]: https://github.com/1Hive/pollen/tree/55a2a57ee3f8969189af3964865cff0262778653

wchargin-branch: github-retry-rate-limits

### CODE REVIEW

**Comment by wchargin** [comment]
Let me know if you’d like me to perform a manual test of this against a
large repository.

**Review by decentralion — APPROVED** [review]

**Comment by decentralion** [comment]
Yeah, please don't merge until the manual test succeeds.

**Review by wchargin — COMMENTED** [review]
> Yeah, please don't merge until the manual test succeeds.

Done; mind checking that the test plan checks out to you?

**Comment by decentralion** [comment]
Nice! Looks good to me. I read the test plan.

**Pull request merged**
