### PR TITLE
Activity table colors

### PR DESCRIPTION
**Pull request by BrianBelhumeur**
# Description
Pursuant to Issue #2260, this PR simply adds color and a bit of styling for the text inside the activity table.

Notes:
- The variable text atop the table is handled by PR #2737 
- Date label will be formatted properly by a new PR after that PR has landed

# Test Plan
- Filtered by type with checkboxes and confirmed that different contributor types have appropriate text colors
- Confirmed averages are italic
- Apparently there's not a real bold font weight for the font we're using, so the bold styles don't come through

## Color for Bots and Projects
Screen Shot 2021-02-09 at 23 05 30

## Color for participants
Screen Shot 2021-02-09 at 23 05 57

### CODE REVIEW

**Review by hammadj — APPROVED** [review]
Might need a rebase since there's 21 commits in this PR. Also, would be nice to have a screenshot next time to see what the visual changes look like without having to run it locally.

Otherwise, looks good!

**Comment by KuraFire** [comment]
+1 to what @hammadj said: please add comparison screenshots to visual/UI-related PRs. It's hard enough for me to keep my local instance to work, since the world of web software development is still fragile AF despite decades of time to fix it; throwing in non-main branches to test is a huge ask currently, a time sink I would like to avoid if all I'm doing is verifying a style or UI layout.

**Comment by BrianBelhumeur** [comment]
Gotcha. Screenshots added for posterity, will include in the future.

**Comment by KuraFire** [comment]
I guess I should've been a little clearer @BrianBelhumeur: I couldn't do a review without screenshots (due to my broken local instance). I would appreciate getting the chance to review before merging, and "making a comment" was not a review ;)

As this is now merged, I can't request a (temporary) change to the Cred color because it doesn't work well on our old background color, and I don't know when that color will be updated to the future/new one, `#0C1B26`.

**Pull request merged**
