### PR TITLE
Discourse CLI cleanup

### PR DESCRIPTION
**Pull request by Beanow**
I had these two changes floating around that don't fall neatly in other PRs.

- `--discourse-username DISCOURSE_USERNAME` was removed, but is still in the help text.
- `projectId` derivation from urls was simplified in #1433, but we're removing the multiple server aspect, so here it is inlined into the existing code.

### CODE REVIEW

**Comment by decentralion** [comment]
For the simplified projectid generation -- what is the [test plan](https://github.com/sourcecred/sourcecred/blob/master/CONTRIBUTING.md#test-plan)?

**Comment by Beanow** [comment]
> For the simplified projectid generation -- what is the [test plan](https://github.com/sourcecred/sourcecred/blob/master/CONTRIBUTING.md#test-plan)?

I've had this change in place for a while in wip branches, where I ran a lot of manual `bin/sourcecred.js discourse` calls. I think the wanted output (some deterministic string that works as a project ID) isn't very critical to warrant factoring out into a utility function and unit testing it. Instead if test coverage for CLI code is a concern I would suggest we do integration tests at the command level.

**Comment by decentralion** [comment]
Cool, I really just want literally what's described in the doc:
> Describe what someone should do to verify that your changes are correct. This can include automated tests, manual tests, or tests of the form “verify that when you change the code in this way, you see this effect.” 

In this case, maybe the test plan is just:

run `yarn backend`
run `node bin/sourcecred.js discourse sourcecred-test.discourse.group`
observe that the load completes without any url parsing issues

**Comment by decentralion** [comment]
Actually, I think this results in a slight but meaningful regression in functionality.

Consider the following command: `node bin/sourcecred.js discourse discourse.sourcecred.io`.

Before:
```
❯ node bin/sourcecred.js discourse discourse.sourcecred.io                                                                                                              sourcecred/git/remotes/origin/HEAD
fatal: expected server url to start with 'https://' or 'http://'
fatal: run 'sourcecred help discourse' for help
  GO   load-discourse.sourcecred.io
  GO   discourse
  GO   discourse/topics
Error: invalid server url: discourse.sourcecred.io
    at Fetcher._fetch (webpack:///./src/plugins/discourse/fetch.js?:32:482)
    at Fetcher.latestTopicId (webpack:///./src/plugins/discourse/fetch.js?:32:761)
    at Mirror.update (webpack:///./src/plugins/discourse/mirror.js?:44:3032)
    at loadDiscourse (webpack:///./src/plugins/discourse/loadDiscourse.js?:14:514)
    at discourseGraph (webpack:///./src/api/load.js?:29:860)
    at load (webpack:///./src/api/load.js?:34:82)
    at async command (webpack:///./src/cli/discourse.js?:12:1563)
```

After:
```
❯ node bin/sourcecred.js discourse discourse.sourcecred.io                                                                                                           sourcecred/git/pr/discourse-clean-cli
  GO   load-discourse.sourcecred.io
  GO   discourse
  GO   discourse/topics
Error: invalid server url: discourse.sourcecred.io
    at Fetcher._fetch (webpack:///./src/plugins/discourse/fetch.js?:32:482)
    at Fetcher.latestTopicId (webpack:///./src/plugins/discourse/fetch.js?:32:761)
    at Mirror.update (webpack:///./src/plugins/discourse/mirror.js?:44:3032)
    at loadDiscourse (webpack:///./src/plugins/discourse/loadDiscourse.js?:14:514)
    at discourseGraph (webpack:///./src/api/load.js?:29:860)
    at load (webpack:///./src/api/load.js?:34:82)
    at async command (webpack:///./src/cli/discourse.js?:12:1355)
```

I think the "expected serverUrl to start with http//: or https://" message is very useful feedback for someone learning to use the plugin.

**Comment by Beanow** [comment]
Got it, I've restored the die statement.

Mistook the test plan for how it's been tested vs how others should test.

**Pull request merged**
