### PR TITLE
Refactor Explorer to Functional Components

### PR DESCRIPTION
**Pull request by hammadj**
Split up the mega-component into three smaller functional components. Can move them to separate files,
kept them in the same one to make it easier to review changes. This will allow us to use memoized selectors
for the cred-view data, making it easier and more performant to compute derived state on the client side.

Test Plan:
Ensure the Explorer functions as it was before the refactor (changing weights, filters, etc)

paired with @topocount

### CODE REVIEW

**Review by topocount — CHANGES_REQUESTED** [review]
I've pushed a fix the for the slider dialog being stuck open and not responding to the show/hide button.

I'm currently unable to recompute cred after changing some weights. It looks like the `paramsUpToDate` boolean might not be updating correctly.

**Comment by hammadj** [comment]
@topocount Fixed!

**Review by topocount — COMMENTED** [review]
I'm still getting an error when attempting to recompute cred after changing the sliders. From the browser console:
```
TypeError: Cannot read property 'entries' of undefined
    at Module.merge (main.70f42eda.js:206623)
    at overrideWeights (main.70f42eda.js:206582)
    at CredView.recompute (main.70f42eda.js:204963)
    at recomputeCred (main.70f42eda.js:206862)
    at HTMLUnknownElement.callCallback (main.70f42eda.js:153664)
    at Object.invokeGuardedCallbackDev (main.70f42eda.js:153713)
    at invokeGuardedCallback (main.70f42eda.js:153768)
    at invokeGuardedCallbackAndCatchFirstError (main.70f42eda.js:153782)
    at executeDispatch (main.70f42eda.js:153865)
    at executeDispatchesInOrder (main.70f42eda.js:153890)
```

**Comment by topocount** [comment]
I also want to get signoff from @befitsandpiper to ensure that this won't be creating any conflicts with his work.

**Review by topocount — APPROVED** [review]
@hammadj I noticed that your updates made it much easier to do some performance tracing, and moreover discovered that your changes have already improved render performance quite a bit :100: 

I've added some further optimizations (that I don't believe are hacky) and UX improvements.

I also fixed the bug that my last review revealed.

Please review my changes back, before merge!

**Comment by hammadj** [comment]
@topocount awesome, thanks for the optimizations! I see you're enjoying the React profiler ;)

**Pull request merged**
